=== DmitryKersh/bugs-all/src/main/resources/layout.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="stateType" final="restriction" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="BUG" />
            <xs:enumeration value="QUEEN" />
            <xs:enumeration value="WALL" />
            <xs:enumeration value="UNAVAILABLE" />
            <xs:enumeration value="FREE" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tileType">
        <xs:sequence>
            <xs:element name="Id" type="xs:string"/>
            <xs:element name="OwnerNumber" type="xs:nonNegativeInteger"/>
            <xs:element name="State" type="stateType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="DefaultValue" type="xs:integer"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tileListType">
        <xs:sequence>
            <xs:element name="Tile" type="tileType"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paramListType">
        <xs:sequence>
            <xs:element name="Param" type="paramType"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Layout">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Description" type="xs:string" />
                <xs:element name="Parameters" type="paramListType"/>
                <xs:element name="Tiles" type="tileListType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DmitryKersh/bugs-all/src/main/resources/layout_example.xml
<?xml version="1.0" encoding="utf-8"?>
<Layout xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='layout.xsd'>
	<Description>Layout Example</Description>
	<Parameters>
		<Param>
			<Name>board_height</Name>
			<DefaultValue>10</DefaultValue>
			<Description>Board height</Description>
		</Param>
	</Parameters>
	<Tiles>
		<Tile>
			<Id>0</Id>
			<OwnerNumber>0</OwnerNumber>
			<State>BUG</State>
		</Tile>
        <Tile>
            <Id>1</Id>
            <OwnerNumber>0</OwnerNumber>
            <State>BUG</State>
        </Tile>
        <Tile>
            <Id>10</Id>
            <OwnerNumber>1</OwnerNumber>
            <State>BUG</State>
        </Tile>
        <Tile>
            <Id>board_height $- 3</Id>
            <OwnerNumber>1</OwnerNumber>
            <State>BUG</State>
        </Tile>
	</Tiles>
</Layout>
